analysis:
  n_cores: 1
hpc:
  hpc_mode: false
  iterations_per_update: 5000
model:
  ignore_prior_limits: false
output:
  force_pickle_overwrite: false
  identifier_version: 4
  info_whitespace_length: 80
  log_file: output.log
  log_level: INFO
  log_to_file: false
  model_results_decimal_places: 3
  remove_files: false
  samples_to_csv: false
parallel:
  warn_environment_variables: true
profiling:
  parallel_profile: false
  repeats: 1
  should_profile: false
test:
  check_preloads: false
  exception_override: false
  parallel_profile: false
