DownhillSimplex:
  initialize:
    method: prior
  printing:
    silence: false
  prior_passer:
    sigma: 3.0
    use_errors: true
    use_widths: true
  search:
    disp: 1
    ftol: 0.0001
    full_output: 0
    maxfun: null
    maxiter: null
    retall: 0
    xtol: 0.0001
  updates:
    iterations_per_update: 11
    log_every_update: 1
    model_results_every_update: 1
    remove_state_files_at_end: true
    visualize_every_update: 1
Drawer:
  initialize:
    ball_lower_limit: 0.49
    ball_upper_limit: 0.51
    method: prior
  printing:
    silence: false
  prior_passer:
    sigma: 3.0
    use_errors: true
    use_widths: true
  search:
    total_draws: 10
  updates:
    iterations_per_update: 500
    remove_state_files_at_end: true
LBFGS:
  initialize:
    ball_lower_limit: 0.49
    ball_upper_limit: 0.51
    method: prior
  options:
    disp: false
    eps: 1.0e-08
    ftol: 2.220446049250313e-09
    gtol: 1.0e-05
    iprint: -1.0
    maxcor: 10
    maxfun: 15000
    maxiter: 15000
    maxls: 20
  printing:
    silence: false
  prior_passer:
    sigma: 3.0
    use_errors: true
    use_widths: true
  search:
    tol: null
  updates:
    iterations_per_update: 11
    log_every_update: 1
    model_results_every_update: 1
    remove_state_files_at_end: true
    visualize_every_update: 1
PySwarmsGlobal:
  initialize:
    ball_lower_limit: 0.49
    ball_upper_limit: 0.51
    method: prior
  parallel:
    number_of_cores: 1
  printing:
    silence: false
  prior_passer:
    sigma: 3.0
    use_errors: true
    use_widths: true
  run:
    iters: 2000
  search:
    cognitive: 0.1
    ftol: -.inf
    inertia: 0.3
    n_particles: 50
    social: 0.2
  updates:
    iterations_per_update: 11
    log_every_update: 1
    model_results_every_update: 1
    remove_state_files_at_end: true
    visualize_every_update: 1
PySwarmsLocal:
  initialize:
    ball_lower_limit: 0.49
    ball_upper_limit: 0.51
    method: prior
  parallel:
    number_of_cores: 1
  printing:
    silence: false
  prior_passer:
    sigma: 3.0
    use_errors: true
    use_widths: true
  run:
    iters: 2000
  search:
    cognitive: 0.1
    ftol: -.inf
    inertia: 0.3
    minkowski_p_norm: 2
    n_particles: 50
    number_of_k_neighbors: 3
    social: 0.2
  updates:
    iterations_per_update: 11
    log_every_update: 1
    model_results_every_update: 1
    remove_state_files_at_end: true
    visualize_every_update: 1
