Gaussian:
  centre:
    gaussian_limits:
      lower: 0.0
      upper: 1.0
    lower_limit: 0.0
    type: Uniform
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 1.0
  normalization:
    gaussian_limits:
      lower: 0.0
      upper: 1.0
    lower_limit: 0.0
    type: Uniform
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 1.0
  sigma:
    gaussian_limits:
      lower: 0.0
      upper: 1.0
    lower_limit: 0.0
    type: Uniform
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 1.0


PhysicalNFW:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 1.0
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 1.0
  ell_comps_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    width_modifier:
      type: Absolute
      value: 0.2
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    width_modifier:
      type: Absolute
      value: 0.2
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  log10m:
    type: Uniform
    lower_limit: 6.0
    upper_limit: 18.0
  concentration:
    type: Uniform
    lower_limit: 1.0
    upper_limit: 20.0