centre_0:
  limits:
    lower: -inf
    upper: inf
  lower_limit: 0.0
  type: Uniform
  upper_limit: 100.0
  width_modifier:
    type: Absolute
    value: 20.0
centre_1:
  limits:
    lower: -inf
    upper: inf
  lower_limit: 0.0
  type: Uniform
  upper_limit: 100.0
  width_modifier:
    type: Absolute
    value: 20.0
normalization:
  limits:
    lower: 0.0
    upper: inf
  lower_limit: 1.0e-06
  type: LogUniform
  upper_limit: 1000000.0
  width_modifier:
    type: Relative
    value: 0.5
sigma:
  limits:
    lower: 0.0
    upper: inf
  lower_limit: 0.0
  type: Uniform
  upper_limit: 25.0
  width_modifier:
    type: Relative
    value: 0.5
